apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-emptydir        # add namespace: dev  (or other) if you need one
spec:
  volumes:
    - name: data
      emptyDir: {}                    # ephemeral volume, erased when the Pod disappears

  containers:
    - name: alpine1
      image: alpine
      command: ["/bin/sleep", "999999"]
      volumeMounts:
        - name: data
          mountPath: /alpine1

    - name: alpine2
      image: alpine
      command: ["/bin/sleep", "999999"]
      volumeMounts:
        - name: data
          mountPath: /alpine2

