apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: dev
  labels:
    app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - name: nginx
          image: greenzmey/details-app:latest
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/sites-available
            - name: variables
              mountPath: /dir
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-custom-config
        - name: variables
          configMap:
            name: declare-vars

