apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/shared
    server: 192.168.68.106  # <-- Your host's LAN IP
  persistentVolumeReclaimPolicy: Retain

