apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: dev
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 1234;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
                                                                                                                                                                                         

