apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: container1
      image: nginx
      volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-8080.conf
      ports:
        - containerPort: 8080

    - name: container2
      image: nginx
      volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-8081.conf
      ports:
        - containerPort: 8081
  volumes:
    - name: cfg
      configMap:
        name: nginx-port-override
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: container3
      image: nginx
      volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-8080.conf
      ports:
        - containerPort: 8080

    - name: container4
      image: nginx
      volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-8081.conf
      ports:
        - containerPort: 8081

    - name: container5
      image: nginx
      volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-8000.conf
      ports:
        - containerPort: 8000
  volumes:
    - name: cfg
      configMap:
        name: nginx-port-override
